name: Build Windows EXE

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"

      - name: Install UPX
        run: |
          choco install upx -y
        shell: powershell

      - name: Tidy modules
        run: go mod tidy

      - name: Build executable with ldflags
        run: go build -ldflags="-s -w" -o PrinterManager.exe

      - name: Compress with UPX
        run: upx --best --lzma PrinterManager.exe

      - name: Upload compressed EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PrinterManager
          path: PrinterManager.exe

      - name: Release (optional)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: PrinterManager.exe
