name: Build Windows EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod tidy

    - name: Build exe
      run: go build -ldflags="-H=windowsgui" -o printergui.exe main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: printergui-exe
        path: printergui.exe
